// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';


class Location implements SupadartClass<Location> {
  final BigInt id;
  final DateTime createdAt;
  final String? name;

  const Location({
    required this.id,
    required this.createdAt,
    this.name,
  });

  static String get table_name => 'location';
  static String get c_id => 'id';
  static String get c_createdAt => 'created_at';
  static String get c_name => 'name';

  static List<Location> converter(List<Map<String, dynamic>> data) {
    return data.map(Location.fromJson).toList();
  }
  static Location converterSingle(Map<String, dynamic> data) {
    return Location.fromJson(data);
  }
  static Map<String, dynamic> _generateMap({
    BigInt? id,
    DateTime? createdAt,
    String? name,
  }) {
    return {
      if (id != null) 'id': id.toString(),
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (name != null) 'name': name,
    };
  }
  static Map<String, dynamic> insert({
    BigInt? id,
    DateTime? createdAt,
    String? name,
  }) {
    return _generateMap(
      id: id,
      createdAt: createdAt,
      name: name,
    );
  }
  static Map<String, dynamic> update({
    BigInt? id,
    DateTime? createdAt,
    String? name,
  }) {
    return _generateMap(
      id: id,
      createdAt: createdAt,
      name: name,
    );
  }
  factory Location.fromJson(Map<String, dynamic> jsonn) {
    return Location(
      id: jsonn['id'] != null ? BigInt.parse(jsonn['id'].toString()) : BigInt.from(0),
      createdAt: jsonn['created_at'] != null ? DateTime.parse(jsonn['created_at'].toString()) : DateTime.fromMillisecondsSinceEpoch(0),
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
    );
  }

  static Object New({
    BigInt? id,
    DateTime? createdAt,
    String? name,
  }) {
    return {
      if (id != null) 'id': id,
      if (createdAt != null) 'created_at': createdAt,
      if (name != null) 'name': name,
    };
  }
  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      createdAt: createdAt,
      name: name,
    );
  }
  Location copyWith({
    BigInt? id,
    DateTime? createdAt,
    String? name,
  }) {
    return Location(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      name: name ?? this.name,
    );
  }

}

