// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';


class Photo implements SupadartClass<Photo> {
  final DateTime createdAt;
  final String? url;
  final String id;
  final String? propertyid;

  const Photo({
    required this.createdAt,
    this.url,
    required this.id,
    this.propertyid,
  });

  static String get table_name => 'photo';
  static String get c_createdAt => 'created_at';
  static String get c_url => 'url';
  static String get c_id => 'id';
  static String get c_propertyid => 'propertyid';

  static List<Photo> converter(List<Map<String, dynamic>> data) {
    return data.map(Photo.fromJson).toList();
  }
  static Photo converterSingle(Map<String, dynamic> data) {
    return Photo.fromJson(data);
  }
  static Map<String, dynamic> _generateMap({
    DateTime? createdAt,
    String? url,
    String? id,
    String? propertyid,
  }) {
    return {
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (url != null) 'url': url,
      if (id != null) 'id': id,
      if (propertyid != null) 'propertyid': propertyid,
    };
  }
  static Map<String, dynamic> insert({
    DateTime? createdAt,
    String? url,
    String? id,
    String? propertyid,
  }) {
    return _generateMap(
      createdAt: createdAt,
      url: url,
      id: id,
      propertyid: propertyid,
    );
  }
  static Map<String, dynamic> update({
    DateTime? createdAt,
    String? url,
    String? id,
    String? propertyid,
  }) {
    return _generateMap(
      createdAt: createdAt,
      url: url,
      id: id,
      propertyid: propertyid,
    );
  }
  factory Photo.fromJson(Map<String, dynamic> jsonn) {
    return Photo(
      createdAt: jsonn['created_at'] != null ? DateTime.parse(jsonn['created_at'].toString()) : DateTime.fromMillisecondsSinceEpoch(0),
      url: jsonn['url'] != null ? jsonn['url'].toString() : '',
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      propertyid: jsonn['propertyid'] != null ? jsonn['propertyid'].toString() : '',
    );
  }

  static Object New({
    DateTime? createdAt,
    String? url,
    String? id,
    String? propertyid,
  }) {
    return {
      if (createdAt != null) 'created_at': createdAt,
      if (url != null) 'url': url,
      if (id != null) 'id': id,
      if (propertyid != null) 'propertyid': propertyid,
    };
  }
  Map<String, dynamic> toJson() {
    return _generateMap(
      createdAt: createdAt,
      url: url,
      id: id,
      propertyid: propertyid,
    );
  }
  Photo copyWith({
    DateTime? createdAt,
    String? url,
    String? id,
    String? propertyid,
  }) {
    return Photo(
      createdAt: createdAt ?? this.createdAt,
      url: url ?? this.url,
      id: id ?? this.id,
      propertyid: propertyid ?? this.propertyid,
    );
  }

}

