// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';


class Property implements SupadartClass<Property> {
  final DateTime createdAt;
  final String? title;
  final String? price;
  final String? description;
  final String? project;
  final String? location;
  final String? finalPrice;
  final String? owner;
  final String? unitType;
  final String? paymentType;
  final double? percentage;
  final String? type;
  final String? deliveryDate;
  final int? bedroom;
  final int? bathroom;
  final int? area;
  final int? floor;
  final double? Maintenance;
  final double? payed;
  final double? instalment;
  final double? offer;
  final String? creator;
  final String id;
  final String? downPayment;

  const Property({
    required this.createdAt,
    this.title,
    this.price,
    this.description,
    this.project,
    this.location,
    this.finalPrice,
    this.owner,
    this.unitType,
    this.paymentType,
    this.percentage,
    this.type,
    this.deliveryDate,
    this.bedroom,
    this.bathroom,
    this.area,
    this.floor,
    this.Maintenance,
    this.payed,
    this.instalment,
    this.offer,
    this.creator,
    required this.id,
    this.downPayment,
  });

  static String get table_name => 'property';
  static String get c_createdAt => 'created_at';
  static String get c_title => 'title';
  static String get c_price => 'price';
  static String get c_description => 'description';
  static String get c_project => 'project';
  static String get c_location => 'location';
  static String get c_finalPrice => 'final_price';
  static String get c_owner => 'owner';
  static String get c_unitType => 'unit_type';
  static String get c_paymentType => 'payment_type';
  static String get c_percentage => 'percentage';
  static String get c_type => 'type';
  static String get c_deliveryDate => 'delivery_date';
  static String get c_bedroom => 'bedroom';
  static String get c_bathroom => 'bathroom';
  static String get c_area => 'area';
  static String get c_floor => 'floor';
  static String get c_Maintenance => 'Maintenance';
  static String get c_payed => 'payed';
  static String get c_instalment => 'instalment';
  static String get c_offer => 'offer';
  static String get c_creator => 'creator';
  static String get c_id => 'id';
  static String get c_downPayment => 'down_payment';

  static List<Property> converter(List<Map<String, dynamic>> data) {
    return data.map(Property.fromJson).toList();
  }
  static Property converterSingle(Map<String, dynamic> data) {
    return Property.fromJson(data);
  }
  static Map<String, dynamic> _generateMap({
    DateTime? createdAt,
    String? title,
    String? price,
    String? description,
    String? project,
    String? location,
    String? finalPrice,
    String? owner,
    String? unitType,
    String? paymentType,
    double? percentage,
    String? type,
    String? deliveryDate,
    int? bedroom,
    int? bathroom,
    int? area,
    int? floor,
    double? Maintenance,
    double? payed,
    double? instalment,
    double? offer,
    String? creator,
    String? id,
    String? downPayment,
  }) {
    return {
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (title != null) 'title': title,
      if (price != null) 'price': price,
      if (description != null) 'description': description,
      if (project != null) 'project': project,
      if (location != null) 'location': location,
      if (finalPrice != null) 'final_price': finalPrice,
      if (owner != null) 'owner': owner,
      if (unitType != null) 'unit_type': unitType,
      if (paymentType != null) 'payment_type': paymentType,
      if (percentage != null) 'percentage': percentage.toString(),
      if (type != null) 'type': type,
      if (deliveryDate != null) 'delivery_date': deliveryDate,
      if (bedroom != null) 'bedroom': bedroom,
      if (bathroom != null) 'bathroom': bathroom,
      if (area != null) 'area': area,
      if (floor != null) 'floor': floor,
      if (Maintenance != null) 'Maintenance': Maintenance.toString(),
      if (payed != null) 'payed': payed.toString(),
      if (instalment != null) 'instalment': instalment.toString(),
      if (offer != null) 'offer': offer.toString(),
      if (creator != null) 'creator': creator,
      if (id != null) 'id': id,
      if (downPayment != null) 'down_payment': downPayment,
    };
  }
  static Map<String, dynamic> insert({
    DateTime? createdAt,
    String? title,
    String? price,
    String? description,
    String? project,
    String? location,
    String? finalPrice,
    String? owner,
    String? unitType,
    String? paymentType,
    double? percentage,
    String? type,
    String? deliveryDate,
    int? bedroom,
    int? bathroom,
    int? area,
    int? floor,
    double? Maintenance,
    double? payed,
    double? instalment,
    double? offer,
    String? creator,
    String? id,
    String? downPayment,
  }) {
    return _generateMap(
      createdAt: createdAt,
      title: title,
      price: price,
      description: description,
      project: project,
      location: location,
      finalPrice: finalPrice,
      owner: owner,
      unitType: unitType,
      paymentType: paymentType,
      percentage: percentage,
      type: type,
      deliveryDate: deliveryDate,
      bedroom: bedroom,
      bathroom: bathroom,
      area: area,
      floor: floor,
      Maintenance: Maintenance,
      payed: payed,
      instalment: instalment,
      offer: offer,
      creator: creator,
      id: id,
      downPayment: downPayment,
    );
  }
  static Map<String, dynamic> update({
    DateTime? createdAt,
    String? title,
    String? price,
    String? description,
    String? project,
    String? location,
    String? finalPrice,
    String? owner,
    String? unitType,
    String? paymentType,
    double? percentage,
    String? type,
    String? deliveryDate,
    int? bedroom,
    int? bathroom,
    int? area,
    int? floor,
    double? Maintenance,
    double? payed,
    double? instalment,
    double? offer,
    String? creator,
    String? id,
    String? downPayment,
  }) {
    return _generateMap(
      createdAt: createdAt,
      title: title,
      price: price,
      description: description,
      project: project,
      location: location,
      finalPrice: finalPrice,
      owner: owner,
      unitType: unitType,
      paymentType: paymentType,
      percentage: percentage,
      type: type,
      deliveryDate: deliveryDate,
      bedroom: bedroom,
      bathroom: bathroom,
      area: area,
      floor: floor,
      Maintenance: Maintenance,
      payed: payed,
      instalment: instalment,
      offer: offer,
      creator: creator,
      id: id,
      downPayment: downPayment,
    );
  }
  factory Property.fromJson(Map<String, dynamic> jsonn) {
    return Property(
      createdAt: jsonn['created_at'] != null ? DateTime.parse(jsonn['created_at'].toString()) : DateTime.fromMillisecondsSinceEpoch(0),
      title: jsonn['title'] != null ? jsonn['title'].toString() : '',
      price: jsonn['price'] != null ? jsonn['price'].toString() : '',
      description: jsonn['description'] != null ? jsonn['description'].toString() : '',
      project: jsonn['project'] != null ? jsonn['project'].toString() : '',
      location: jsonn['location'] != null ? jsonn['location'].toString() : '',
      finalPrice: jsonn['final_price'] != null ? jsonn['final_price'].toString() : '',
      owner: jsonn['owner'] != null ? jsonn['owner'].toString() : '',
      unitType: jsonn['unit_type'] != null ? jsonn['unit_type'].toString() : '',
      paymentType: jsonn['payment_type'] != null ? jsonn['payment_type'].toString() : '',
      percentage: jsonn['percentage'] != null ? double.parse(jsonn['percentage'].toString()) : 0.0,
      type: jsonn['type'] != null ? jsonn['type'].toString() : '',
      deliveryDate: jsonn['delivery_date'] != null ? jsonn['delivery_date'].toString() : '',
      bedroom: jsonn['bedroom'] != null ? int.parse(jsonn['bedroom'].toString()) : 0,
      bathroom: jsonn['bathroom'] != null ? int.parse(jsonn['bathroom'].toString()) : 0,
      area: jsonn['area'] != null ? int.parse(jsonn['area'].toString()) : 0,
      floor: jsonn['floor'] != null ? int.parse(jsonn['floor'].toString()) : 0,
      Maintenance: jsonn['Maintenance'] != null ? double.parse(jsonn['Maintenance'].toString()) : 0.0,
      payed: jsonn['payed'] != null ? double.parse(jsonn['payed'].toString()) : 0.0,
      instalment: jsonn['instalment'] != null ? double.parse(jsonn['instalment'].toString()) : 0.0,
      offer: jsonn['offer'] != null ? double.parse(jsonn['offer'].toString()) : 0.0,
      creator: jsonn['creator'] != null ? jsonn['creator'].toString() : '',
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      downPayment: jsonn['down_payment'] != null ? jsonn['down_payment'].toString() : '',
    );
  }

  static Object New({
    DateTime? createdAt,
    String? title,
    String? price,
    String? description,
    String? project,
    String? location,
    String? finalPrice,
    String? owner,
    String? unitType,
    String? paymentType,
    double? percentage,
    String? type,
    String? deliveryDate,
    int? bedroom,
    int? bathroom,
    int? area,
    int? floor,
    double? Maintenance,
    double? payed,
    double? instalment,
    double? offer,
    String? creator,
    String? id,
    String? downPayment,
  }) {
    return {
      if (createdAt != null) 'created_at': createdAt,
      if (title != null) 'title': title,
      if (price != null) 'price': price,
      if (description != null) 'description': description,
      if (project != null) 'project': project,
      if (location != null) 'location': location,
      if (finalPrice != null) 'final_price': finalPrice,
      if (owner != null) 'owner': owner,
      if (unitType != null) 'unit_type': unitType,
      if (paymentType != null) 'payment_type': paymentType,
      if (percentage != null) 'percentage': percentage,
      if (type != null) 'type': type,
      if (deliveryDate != null) 'delivery_date': deliveryDate,
      if (bedroom != null) 'bedroom': bedroom,
      if (bathroom != null) 'bathroom': bathroom,
      if (area != null) 'area': area,
      if (floor != null) 'floor': floor,
      if (Maintenance != null) 'Maintenance': Maintenance,
      if (payed != null) 'payed': payed,
      if (instalment != null) 'instalment': instalment,
      if (offer != null) 'offer': offer,
      if (creator != null) 'creator': creator,
      if (id != null) 'id': id,
      if (downPayment != null) 'down_payment': downPayment,
    };
  }
  Map<String, dynamic> toJson() {
    return _generateMap(
      createdAt: createdAt,
      title: title,
      price: price,
      description: description,
      project: project,
      location: location,
      finalPrice: finalPrice,
      owner: owner,
      unitType: unitType,
      paymentType: paymentType,
      percentage: percentage,
      type: type,
      deliveryDate: deliveryDate,
      bedroom: bedroom,
      bathroom: bathroom,
      area: area,
      floor: floor,
      Maintenance: Maintenance,
      payed: payed,
      instalment: instalment,
      offer: offer,
      creator: creator,
      id: id,
      downPayment: downPayment,
    );
  }
  Property copyWith({
    DateTime? createdAt,
    String? title,
    String? price,
    String? description,
    String? project,
    String? location,
    String? finalPrice,
    String? owner,
    String? unitType,
    String? paymentType,
    double? percentage,
    String? type,
    String? deliveryDate,
    int? bedroom,
    int? bathroom,
    int? area,
    int? floor,
    double? Maintenance,
    double? payed,
    double? instalment,
    double? offer,
    String? creator,
    String? id,
    String? downPayment,
  }) {
    return Property(
      createdAt: createdAt ?? this.createdAt,
      title: title ?? this.title,
      price: price ?? this.price,
      description: description ?? this.description,
      project: project ?? this.project,
      location: location ?? this.location,
      finalPrice: finalPrice ?? this.finalPrice,
      owner: owner ?? this.owner,
      unitType: unitType ?? this.unitType,
      paymentType: paymentType ?? this.paymentType,
      percentage: percentage ?? this.percentage,
      type: type ?? this.type,
      deliveryDate: deliveryDate ?? this.deliveryDate,
      bedroom: bedroom ?? this.bedroom,
      bathroom: bathroom ?? this.bathroom,
      area: area ?? this.area,
      floor: floor ?? this.floor,
      Maintenance: Maintenance ?? this.Maintenance,
      payed: payed ?? this.payed,
      instalment: instalment ?? this.instalment,
      offer: offer ?? this.offer,
      creator: creator ?? this.creator,
      id: id ?? this.id,
      downPayment: downPayment ?? this.downPayment,
    );
  }

}

